-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMQCVdpdGNoIGhhdApIYW5kcyBXcmFwBVNjYXJmCld5dmVybiBNYXcNU2hvdWxkZXIgV29sZgpCbGFjayBDYXBlCkZsYW1lIFdyYXALRmVsaW5lIEVhcnMTUnVpbmVkIEtpbmcncyBDcm93bg5DZWxlc3RpYWwgSGFsbwtEYW1hZ2VCb29zdAxXaGFsZSBMYXRlcm4LSGVhbHRoQm9vc3QSQ29vbGRvd25NdWx0aXBsaWVyDkNyaXRpY2FsRGFtYWdlDkhlYXZlbmx5IFdpbmdzAAECAAABAgAyowAAAP8ABQAAAAAA/wEAAAAAAAAwAQB9AAAAAP8BAAAAAAAAMAEAhQEAAAD/AQAAAAAAADABAAgCAAAA/wEAAAAAAAAwAQDpAwAAAP8BAAAAAAAAMAEAxgQAAAD/AQAAAAAAADABAKQFAAAA/wEAAAAAAAAwAQAqBgAAAP8BAAAAAAAAMAEAswcAAAD/AQAAAAAAADABAGUIAAAA/wEAAAAAAAAwAQA/CQAAAOIBDAAwAQBkDQAAAOIBFQAwAQDLFgAAAIIAAgAXAwEDAgMDAwQDBQMGAwcDCAMJAwoDCwIAAAAAAADgPwgBCgsAAAADDAJmZmZmZmbWPwMNApqZmZmZmdk/Aw4CZmZmZmZm1r8DDwIAAAAAAADQPwgECg4AAAAPEAAAABESAAAAExQAAAADEAABAAEYAAwAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAQAAB8AAAABAAAAAACvRzT2g9aKAa+GWM8LF4Vp318jgp2DXvc=

-- https://lua.expert/
return {
	["Witch hat"] = {},
	["Hands Wrap"] = {},
	Scarf = {},
	["Wyvern Maw"] = {},
	["Shoulder Wolf"] = {},
	["Black Cape"] = {},
	["Flame Wrap"] = {},
	["Feline Ears"] = {},
	["Ruined King\'s Crown"] = {},
	["Celestial Halo"] = {},
	["Whale Latern"] = {
		DamageBoost = 0.5
	},
	["Heavenly Wings"] = {
		DamageBoost = 0.35,
		HealthBoost = 0.4,
		CooldownMultiplier = -0.35,
		CriticalDamage = 0.25
	}
}