-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMPBlJhcml0eQZDb21tb24HQml0ZU1pbgdCaXRlTWF4DFByb2dyZXNzR2FpbgxQcm9ncmVzc0xvc3METHVjawlCYXNpYyBSb2QJTGVnZW5kYXJ5CkFuZ2xlciBSb2QITXl0aGljYWwOU2VhIERyYWdvbiBSb2QGU2VjcmV0F05vcm1hbFNlY3JldENhdGNoQ2hhbmNlC0FuZ2VsaWMgUm9kAAECAAABAgAQowAAAP8AAwAAAAAA4gELADABAAgMAAAA4gESADABAG0TAAAA4gEaADABAJsbAAAA4gEiADABAAYjAAAAggACACQDAQMCAwMCAAAAAAAALEADBAIAAAAAAAAyQAMFAgAAAAAAAPA/AwYDBwIAAAAAAAAAAAgGAAEAAAACAwAAAAQFAAAABgcAAAAIBwAAAAkKAAAAAwgDCQIAAAAAAAAkQALNzMzMzMz0PwLNzMzMzMzsPwKamZmZmZnJPwgGAA0AAAACDgAAAAQDAAAABg8AAAAIEAAAAAkRAAAAAwoDCwIAAAAAAAAgQAIAAAAAAAAmQAIAAAAAAAD4PwIAAAAAAADoPwKamZmZmZnZPwgGABQAAAACFQAAAAQWAAAABhcAAAAIGAAAAAkZAAAAAwwDDQIAAAAAAAAUQALNzMzMzMz8PwIzMzMzMzPjPwMOAvyp8dJNYlA/CAcAHAAAAAIdAAAABBUAAAAGHgAAAAgfAAAACR8AAAAgIQAAAAMPAAEAARgAAwABAAAJAAAJAAAJAAAAAQAAAAAANztyBCWPIRW0JVleUsPhLUcjZXAF/xgF

-- https://lua.expert/
return {
	["Basic Rod"] = {
		Rarity = "Common",
		BiteMin = 14,
		BiteMax = 18,
		ProgressGain = 1,
		ProgressLoss = 1,
		Luck = 0
	},
	["Angler Rod"] = {
		Rarity = "Legendary",
		BiteMin = 10,
		BiteMax = 14,
		ProgressGain = 1.3,
		ProgressLoss = 0.9,
		Luck = 0.2
	},
	["Sea Dragon Rod"] = {
		Rarity = "Mythical",
		BiteMin = 8,
		BiteMax = 11,
		ProgressGain = 1.5,
		ProgressLoss = 0.75,
		Luck = 0.4
	},
	["Angelic Rod"] = {
		Rarity = "Secret",
		BiteMin = 5,
		BiteMax = 8,
		ProgressGain = 1.8,
		ProgressLoss = 0.6,
		Luck = 0.6,
		NormalSecretCatchChance = 0.001
	}
}