-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMFDFVuaXRUZW1wbGF0ZQRnYW1lDFR3ZWVuU2VydmljZQpHZXRTZXJ2aWNlDFNvdW5kU2VydmljZQACAgIAAAAHBAAABQIEBwGCAAEAAAAKAQEYAAwAAAAABAAAAQIAE6MAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwL/AgEAAAAAAMADBQAwAwIJBgAAAIICAgAHAwIEAAAAQAMDAwQDBQYAAwEBAAEAARgAAQAAAAAAAQAAAAAABQACAAAEAQAAAAAB

-- https://lua.expert/
game:GetService("TweenService")
game:GetService("SoundService")

return {
	UnitTemplate = function(p1, p2) --[[ UnitTemplate | Line: 10 ]] end
}