-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMKBE5hbWUMc3Bhd25hbGxib3NzB0FsaWFzZXMLRGVzY3JpcHRpb24qSW5zdGFudGx5IHJlc3Bhd24gYWxsIGJvc3NlcyBpbiB0aGUgd29ybGQuBUdyb3VwBUFkbWluBEFyZ3MDc2FiCHNwYXduYWxsAAEEAAABAgAPowAAAOIACAD/AQAAAgAAAG8CCQBvAwoAxQECAwEAAAAwAQAnAgAAAP8BAAAAAAAAMAEA2wcAAACCAAIACwMBAwIDAwMEAwUDBgMHAwgIBQABAAAAAv////8DBAAAAAUGAAAAB/////8DCQMKAAEAARgAAAIAAAAAAAAAAwAAAAABAAAAAACiWbA+eR7bvjozmQ4aXvV70kGnSpCd2j8=

-- https://lua.expert/
return {
	Name = "spawnallboss",
	Description = "Instantly respawn all bosses in the world.",
	Group = "Admin",
	Aliases = { "sab", "spawnall" },
	Args = {}
}