-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMLEkNhbWVyYVR3ZWVuSW5mb19JbhFFeHRlcm5hbFNjYWxlX091dBNDYW1lcmFUd2VlbkluZm9fT3V0CVR3ZWVuSW5mbwNuZXcERW51bQtFYXNpbmdTdHlsZQRCYWNrD0Vhc2luZ0RpcmVjdGlvbgNPdXQCSW4AAQUAAAECACGjAAAA4gADAKQBBgAAFECAbwIHAKQDCwAKJIDApAQOAA0wgMCfAQQCMAEARgAAAACkAQYAABRAgG8CDwCkAwsACiSAwKQEDgANMIDAnwEEAjABAGkBAAAApAEGAAAUQIBvAhAApAMLAAokgMCkBBIAETCAwJ8BBAIwAQCmAgAAAIIAAgATAwEDAgMDBQMAAQIDBAMFBAAUQIACAAAAAAAA0D8DBgMHAwgECiSAwAMJAwoEDTCAwAJmZmZmZmbWPwKamZmZmZnJPwMLBBEwgMAAAQABGAAAAQABAAAAAP8AAAMAAQAAAAD/AAADAAIAAAAA/gAAAAEAAAAAAKTxl8Yg4aVE9Xh9uDCYfuDU6YCyljX9xw==

-- https://lua.expert/
return {
	CameraTweenInfo_In = TweenInfo.new(0.25, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
	ExternalScale_Out = TweenInfo.new(0.35, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
	CameraTweenInfo_Out = TweenInfo.new(0.2, Enum.EasingStyle.Back, Enum.EasingDirection.In)
}