-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- CQMKBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UKR2V0U2VydmljZQdyZXF1aXJlBlNoYXJlZAxXYWl0Rm9yQ2hpbGQERGF0YQtDaGVja2VyRGF0YQpCbHVlUHJpbnRzFFBsYXllclN0YXRzQmx1ZVByaW50AAEGAAABAgAoowAAAKQAAQAAAABAbwICALwAABYDAAAAnwADAqQBBQAAAEBAbwQGALwCANMHAAAAnwIDAm8ECAC8AgLTBwAAAJ8CAwJvBAkAvAIC0wcAAACfAgMAnwEAAqQCBQAAAEBAbwUGALwDANMHAAAAnwMDAm8FCgC8AwPTBwAAAJ8DAwJvBQsAvAMD0wcAAACfAwMAnwIAAv8DAAAAAAAAggMCAAwDAQQAAABAAwIDAwMEBAAAQEADBQMGAwcDCAMJAwoAAQABGAADAAAAAAABAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABMAAABAAAAAAD+yDCqilg/xBNW+Vx0S7J7jtAn3swMWqs=

-- https://lua.expert/
local ReplicatedStorage = game:GetService("ReplicatedStorage")

require(ReplicatedStorage:WaitForChild("Shared"):WaitForChild("Data"):WaitForChild("CheckerData"))
require(ReplicatedStorage:WaitForChild("Shared"):WaitForChild("BluePrints"):WaitForChild("PlayerStatsBluePrint"))

return {}